name: appunti_web_frontend
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.10.0-3.0.dev.flutter-d5ff386abe <3.0.0"

dependencies:
  provider: ^4.3.2
  http: ^0.12.2
  flutter:
    sdk: flutter
  # cupertino_icons: ^0.1.3 # Per il momento lo tolgo, se vogliamo fare una versione iOS lo rimettiamo
  # flutter_secure_storage: ^3.3.3 # Per l'app mobile
  # path_provider: ^1.6.11 # Per l'app mobile


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

flutter:
  uses-material-design: true
